datasets:

  wdbc:
    features_path: data/raw/wdbc/features.csv
    target_path: data/raw/wdbc/target.csv
    target_column: Diagnosis

  adult:
    features_path: data/raw/adult/features.csv
    target_path: data/raw/adult/target.csv
    target_column: income

  bank_marketing:
    features_path: data/raw/bank_marketing/features.csv
    target_path: data/raw/bank_marketing/target.csv
    target_column: y